apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: internal
  name: internal-role
rules:
- apiGroups: 
  - ""
  resources: 
  - pods
  - services
  - configmaps
  verbs: 
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups: 
  - apps
  resources: 
  - deployments
  verbs: 
  - get
  - list
  - watch
  - create
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: internal-rolebinding
  namespace: internal
subjects:
- kind: User
  name: bob
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: internal-role
  apiGroup: rbac.authorization.k8s.io